### ISSUE TITLE
I don't see any tar.gz on netacad download page, as I remember we need to use alien to extract the deb package

### ISSUE THREAD

**Issue by benyaminl** [thiagojack/packettracer-rpm-based#4]
As title state, I don't see any tar.gz on netacad download page, as I remember we need to use alien to extract the deb package. How to you obtain the tar.gz? Would you please elaborate? Thank you
EDIT : Ah I found your old archived code, https://github.com/thiagojack/packettracer_ce8/blob/master/pt730_centos8_install.sh 

It should convert the deb first right?

Thank you. 

Eg(this is on instructor portal, anyway this is same as on student portal, the difference is I don't need to complete 2 hours PT exercise) : 
![image](https://user-images.githubusercontent.com/2817332/198858410-69fd5b36-e1fa-481d-8fc8-f1ed3444090b.png)

**Comment by benyaminl** [comment]
Ah I'm a dumbass... I found it 
https://github.com/thiagojack/packettracer-rpm-based/blob/main/setup.sh#L78 and https://github.com/thiagojack/packettracer_ce8/blob/master/pt730_centos8_install.sh#L16 Are same code to extract the deb package. Thanks!

Would you share this to Cisco community? Because it's really useful man. There are a lot of EL based need this package, but for no reason Cisco doesn't even want to build one, but they still promoting RHEL which is confusing for me...

**Comment by thiagoojack** [comment]
I preferred not to use the `alien` tool using only the `ar` to extract the deb file.
When you talk about "Cisco Community", where exactly is this community?

**Comment by benyaminl** [comment]
@thiagojack https://community.cisco.com/t5/online-tools-and-resources/bd-p/5011-discussions-online-tools-resources should be there, but I don't know whether the script is against the term and condition or not

**Comment by benyaminl** [comment]
@thiagoojack The script is tested on Fedora 37 and works with PK 8.2, could you update the readme?
