### ISSUE TITLE
No browser window opens

### ISSUE THREAD

**Issue by tbunreal** [thiagojack/packettracer-rpm-based#7]
When trying to login with skills for all, no browser window opens making it impossible to login into packet tracer

**Comment by thiagoojack** [comment]
What's your Operating System?

**Comment by tbunreal** [comment]
OpenSuse tumbleweed

**Comment by thiagoojack** [comment]
> 
Show me the output of this command in console: `ldd /opt/pt/bin/PacketTracer | grep not`

**Comment by tbunreal** [comment]
Sure, here it is.

ldd /opt/pt/bin/PacketTracer | grep not
       libssl.so.1.1 => not found
       libcrypto.so.1.1 => not found

**Comment by thiagoojack** [comment]
Try to install the libs not found in your system. In your case, libssl and libcrypto in their respective versions.

**Comment by tbunreal** [comment]
the only packages I could find in the yast software manager were libssl53
and libcrypto50 which did not fix the problem. I did get packet tracer to
work with wine, so if you dont want to put any more effort into helping me
it's ok!

**Comment by thiagoojack** [comment]
I only can try in OpenSUSE Tumbleweed tomorrow.

**Comment by thiagoojack** [comment]
Hello!
I tried with a clean installation of OpenSUSE Tumbleweed and I no have any problem to open login page of Skills for All. Look at this video and you will can see that my installation has some libs that not located, but, has not any warning about libssl and libcrypto.

[cisco_packet_tracer_tumbleweed_skills_for_all.webm](https://user-images.githubusercontent.com/5920212/230684730-6c0d9a66-29de-480c-b105-828c6174aab7.webm)

<br>The package that provides `libssl.so.1.1` and `libcrypto.so.1.1` on OpenSUSE Tumbleweed is `libopenssl1_1`.

![image](https://user-images.githubusercontent.com/5920212/230685970-3104174e-b1bc-4f7b-8c53-8116d0160cd9.png)

**Comment by tbunreal** [comment]
So I managed to install the packages through the command line, but it still
wont open. The cisco network academy button will open a window, just not
skills for all...I tried reinstalling, same issue. Sorry!

**Comment by thiagoojack** [comment]
Does it just open a blank window, like new tab without any address on address bar?

Have you any proxy config in your system? Can you open the below link if you put it directly on the address bar?
https://auth.socialgoodplatform.com/auth/realms/skillsforall/protocol/openid-connect/auth?client_id=02159bbb62514124&openid=&response_type=code&state=3oy7hLdf

**Comment by tbunreal** [comment]
Does not open anything. And no, no proxy configurations and yes I can open
the link.

**Comment by thiagoojack** [comment]
Try to exec Packet Tracer and do all steps that you make before and goes to terminal and run `jourmalctl -xe` to see what's happening when you try to login.

**Comment by thiagoojack** [comment]
Apparently, this problem is not script related. If you find anything that indicates a problem with script, please, report.
